name: build
on: [push, pull_request]
jobs:
  golangci:
    name: Go lint & vet
    runs-on: ubuntu-latest
    # See https://github.com/Dart-Code/Dart-Code/pull/2375
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      matrix:
        go-version: ['1.18']
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: -D errcheck
      - name: go vet
        run: |
          go vet .

  build:
    name: Test Go ${{ matrix.go-version }} / Tarantool ${{ matrix.tarantool-version }}
    runs-on: ubuntu-latest
    # See https://github.com/Dart-Code/Dart-Code/pull/2375
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.18']
        tarantool-version: ['2.9', '2.8', '2.6', '1.10']
    steps:
      - name: Install Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install tarantool ${{ matrix.tarantool-version }}
        uses: tarantool/setup-tarantool@v1
        with:
          tarantool-version: ${{ matrix.tarantool-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: go test -v -timeout 20s
